### PR TITLE
allow interpreter specification w/ prefix arg

### LINKED ISSUE #18: Allow specifying the python interpreter
With a prefix environment to `venv-mkvirtualenv` I'd like to specify which python interpreter to use. This is useful if I want to create a Python 2 virtualenv on a box where Python 3 is the default, or if I want a pypy virtualenv.

### PR DESCRIPTION
**Pull request by porterjamesj**
@Wilfred implemented the prefix arg thing here.

Could you check out this branch and let me know if it works for you? Thanks!

Fixes #18.

### CODE REVIEW

**Comment by Wilfred** [comment]
Thanks for this! @porterjamesj yep, seems to work.

I'm not sure I'd bother with the completion in `venv-get-python-executable` though. I end up with "Python executable ~/pyenvs/whatever/bin/python [Not readable]" in the minibuffer. I think typing `pypy` or `pythonX.Y` is the common case, so I'd just do `(read-string "Python executable: " "python")`.

What do you think?

**Comment by porterjamesj** [comment]
@Wilfred finally got around to cleaning this up, what do you think?

**Comment by Wilfred** [comment]
Thanks for taking the time to do this :+1: 

Looks really good to me!

**Comment by porterjamesj** [comment]
wooo! this was certainly a long time coming for such a simple feature :P

**Pull request merged**
