### PR TITLE
Use modern Travis environment and EVM for Emacs versions

### PR DESCRIPTION
**Pull request by sambrightman**
I noticed that the PPA was rather out of date, and have used EVM
before. I'm about to update its snapshot version and add 25.3 as well.

### CODE REVIEW

**Comment by sambrightman** [comment]
This will pass on re-run because I added 25.3 to evm.

**Comment by porterjamesj** [comment]
Thank you! Hmmm, build still seems to fail after I kicked it: https://travis-ci.org/porterjamesj/virtualenvwrapper.el/jobs/276590475

**Comment by sambrightman** [comment]
Hmm, maybe a transient network problem? I think I've seen that before with cask. Mine passed:

https://travis-ci.org/sambrightman/virtualenvwrapper.el/jobs/276590446

One more bump?

**Comment by porterjamesj** [comment]
giving it a try

**Comment by porterjamesj** [comment]
Yep, looks good. Thank you again! This is great. Caveat emptor though—I've never used evm, so if it breaks or starts doing something weird in the future, I may call on you to help figure it out :)

**Pull request merged**
